import path from "node:path";
import { getPublishedChallengeIds } from "./catalog.mjs";
import { REPOSITORY_ROOT } from "./fs-utils.mjs";
import { optionalRuntimeStatus, SYNTHETIC_MATERIAL_LABEL } from "./optional-routes.mjs";

export const GENERATED_INDEX_PATH = path.join(
  REPOSITORY_ROOT,
  "docs",
  "generated",
  "challenge-index.md",
);
export const GENERATED_SUPPORT_PATH = path.join(
  REPOSITORY_ROOT,
  "docs",
  "generated",
  "support-matrix.md",
);

const GENERATED_NOTICE =
  "<!-- Generated by scripts/render-docs.mjs. Do not edit directly. -->";

function escapeTable(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function challengeLink(challenge, published) {
  return published
    ? `[${challenge.id}](../../${challenge.page})`
    : challenge.id;
}

export function renderChallengeIndex(catalog) {
  const publishedIds = new Set(getPublishedChallengeIds(catalog));
  const rows = catalog.challenges.map((challenge) => {
    const published = publishedIds.has(challenge.id);
    const status = published ? "公開中" : "計画中";
    const material = published ? sourceSummary(challenge) : "-";
    return `| ${challengeLink(challenge, published)} | ${status} | ${escapeTable(challenge.title)} | ${escapeTable(challenge.track)} | ${escapeTable(challenge.feature ?? "未定")} | ${material} |`;
  });

  return `${GENERATED_NOTICE}

# Challenge Index

全45 Challengeの公開状況です。公開中のChallengeはリンク先だけで完結し、過去のLABを読む必要はありません。

| ID | 状態 | Challenge | Track | 対象機能 | 教材の由来 |
|---|---|---|---|---|---|
${rows.join("\n")}
`;
}

function sourceSummary(challenge) {
  if (challenge.sourceKind === "synthetic") {
    return `合成教材 (${SYNTHETIC_MATERIAL_LABEL})`;
  }
  if (challenge.sourceKind === "baseline") return "固定baseline source";
  throw new Error(`Unknown sourceKind for ${challenge.id}: ${challenge.sourceKind}`);
}

export function renderSupportMatrix(catalog) {
  const publishedIds = new Set(getPublishedChallengeIds(catalog));
  const rows = catalog.challenges.map((challenge) => {
    if (!publishedIds.has(challenge.id)) {
      return `| ${challenge.id} | 計画中 | - | - | - | 公開を待ってください | - |`;
    }

    const guides = challenge.optionalRoutes.map((route) =>
      `[${escapeTable(route.title)}](../../${route.page}) (${route.liveStatus}; Runtime: ${optionalRuntimeStatus(route)})`,
    ).join("<br>") || "-";
    return `| [${challenge.id}](../../${challenge.page}) | 公開中 | ${escapeTable(challenge.isolation.tier)} | ${escapeTable(challenge.isolation.conditionStrategy)} | ${escapeTable(challenge.support.primary)} | ${escapeTable(challenge.support.fallback)} | ${guides} |`;
  });

  return `${GENERATED_NOTICE}

# Support Matrix

機能を利用できない場合でも、各ChallengeのFallbackで学習可能性を保ちます。\`blocked\` や \`unsupported\` も有効な観測結果です。

任意リンクはガイド・準備確認のみです。\`live-unobserved\` は実機未確認、\`not-checked\` は準備完了の判定ではありません。ガイドの閲覧は本編の改善やRuntime検証成功には数えません。

| ID | 状態 | 分離Tier | 比較条件 | 通常経路 | Support / Fallback | 任意ガイド（実行サポートではない） |
|---|---|---|---|---|---|---|
${rows.join("\n")}
`;
}

export function renderGeneratedDocs(catalog) {
  return new Map([
    [GENERATED_INDEX_PATH, renderChallengeIndex(catalog)],
    [GENERATED_SUPPORT_PATH, renderSupportMatrix(catalog)],
  ]);
}

export function validateGeneratedDocContents(catalog, actualContentsByPath) {
  const errors = [];
  for (const [filePath, expectedContents] of renderGeneratedDocs(catalog)) {
    if (actualContentsByPath.get(filePath) !== expectedContents) {
      errors.push({
        code: "GENERATED_DOC_STALE",
        message: `${path.relative(REPOSITORY_ROOT, filePath)} is stale`,
      });
    }
  }
  return errors;
}
